import { Hono } from 'hono';
import { redis, reddit, context } from '@devvit/web/server';
import { keys, formatMonth } from '../storage/keys';
import { getRules } from '../core/rules';
import { runAggregation } from '../core/aggregation';

export const scheduler = new Hono();

scheduler.post('/daily-aggregation', async (c) => {
  try {
    const rules = await getRules();
    const ruleNames = rules.map((r) => r.shortName);

    await runAggregation(ruleNames);

    await Promise.all(
      ruleNames.map(async (rule) => {
        const count = await redis.zCard(keys.annotations(rule));
        if (count > 50) {
          await redis.zRemRangeByRank(keys.annotations(rule), 0, count - 51);
        }
        const trendCount = await redis.zCard(keys.trend(rule));
        if (trendCount > 52) {
          await redis.zRemRangeByRank(keys.trend(rule), 0, trendCount - 53);
        }
      })
    );

    console.log('RuleForge: Daily aggregation complete');
    return c.json({}, 200);
  } catch (error) {
    console.error('Daily aggregation error:', error);
    return c.json({ error: String(error) }, 400);
  }
});

scheduler.post('/weekly-report', async (c) => {
  try {
    const stats = await redis.hGetAll(keys.aggStats());
    const problems = await redis.hGetAll(keys.problemRules());
    const monthKey = formatMonth(new Date());
    const topRulesRaw = await redis.zRange(keys.ruleRemovals(monthKey), 0, 4, { reverse: true });

    let body = `# RuleForge Weekly Report\n\n`;
    body += `**Generated:** ${new Date().toUTCString()}\n\n---\n\n`;
    body += `## Overview\n\n`;
    body += `| Metric | Value |\n|---|---|\n`;
    body += `| Health Score | **${stats.healthScore ?? '100'}**/100 |\n`;
    body += `| Total Actions | ${stats.totalActions ?? '0'} |\n`;
    body += `| Removals | ${stats.totalRemovals ?? '0'} |\n`;
    body += `| Approvals | ${stats.totalApprovals ?? '0'} |\n`;
    body += `| Overrides | ${stats.totalOverrides ?? '0'} |\n\n`;

    body += `## Top Enforced Rules\n\n`;
    for (const r of topRulesRaw) {
      body += `- **${r.member}**: ${r.score} removals\n`;
    }

    const flagged = Object.entries(problems)
      .map(([rule, json]) => ({ rule, ...JSON.parse(json) }))
      .filter((p: { flagged: boolean }) => p.flagged);

    if (flagged.length > 0) {
      body += `\n## Problem Rules\n\n`;
      for (const p of flagged) {
        body += `- **${p.rule}**: ${Math.round(p.overrideRate * 100)}% override rate (${p.annotationCount} annotations)\n`;
      }
    } else {
      body += `\n## All Rules Healthy\n\nNo rules exceed the override threshold.\n`;
    }

    body += `\n---\n*Generated by RuleForge*`;

    const subredditName = context.subredditName;
    const dateStr = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
    if (subredditName) {
      await reddit.submitPost({
        subredditName,
        title: `RuleForge Weekly Report — ${dateStr}`,
        text: body,
      });

      try {
        if (typeof reddit.sendPrivateMessage === 'function') {
          await reddit.sendPrivateMessage({
            to: `/r/${subredditName}`,
            subject: `RuleForge Weekly Report — ${dateStr}`,
            text: body,
          });
        }
      } catch (mailErr) {
        console.warn('Modmail send failed (non-critical):', mailErr);
      }
    }

    console.log('RuleForge: Weekly report posted');
    return c.json({}, 200);
  } catch (error) {
    console.error('Weekly report error:', error);
    return c.json({ error: String(error) }, 400);
  }
});
